openapi: 3.0.0
info:
  version: 1.0.0
  title: Sample API
  description: A sample API to illustrate OpenAPI concepts
paths:
  /applications:
    get:
      operationId: getApplications
      description: Returns a list of applications     
      responses:
        '200':
          $ref: "#/components/responses/Applications"
        '204':
          description: No applications
components:
  responses:
    Applications:
      description: List of applications
      content: 
        application/json:
          schema: 
            type: array
            items:
              $ref: '#/components/schemas/Application'
  schemas:
    Application:
      type: object
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: Renewal
        created:
          type: string
          format: date-time
        attachments:
          items:
            $ref: '#/components/schemas/Attachment'
      required:
        - id
        - title
        - created
    Attachment:
      type: object
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: Car payment
        created:
          type: string
          format: date-time